name = "Penopt"
uuid = "fb8f6f4e-b8f1-11e9-2b95-bdba3fec731e"
authors = ["Michal Kocvara <kocvara@penopt.com>", "Beno√Æt Legat <benoit.legat@gmail.com>", "Michael Stingl <mstingl@penopt.com>"]
version = "0.0.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[extras]
MathOptInterface = "0.9.22"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
